.\" Start of Linux Power User
.sec
Linux Power User
.reg
.RS
.sp -.1
.bul
Minimalist CLI based workflow following Unix Philosophy for maximum productivity ( vim, tmux )
.bul
Uses and contributes to minimalist source based distribution ( venomlinux )
.bul
VenomLinux is simply Linux From Scratch (LFS) with a basic shell based package manager
.bul
Simple tasks should be written in bash, programs written in C
.bul
Contributes to open source projects ( mutt, venomlinux )
.RE
.reg
.sp .4
